#!/bin/bash
# cistrome-stats
# Author: Will Zhang

if [ $# -eq 0 ]
then
    echo "Tool:    cistrome-stats"
    echo "Summary: print table of cistrome overlap statistics (number of peaks, percent of peak overlap, width of peaks, FDR of peaks) both mean and standard deviation given an input file (generated by cistrome-overlap.sh)"
    echo "Usage:   ./cistrome-stats.sh input-file"
    exit 1
fi

if [ $# != 1 ]
then
    echo "Error: incorrect number of arguments given."
    exit 1
fi

file=$1

# Sort the overlap file by the histone mark.
sort -k2,2 -t';' $file -o tmp-sorted.txt 
